<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title><?php echo $properties->system_information->name; ?></title>

<link rel="stylesheet" href="<?php echo $config["assets"] . 'css' . DS . "style.css?v=". $properties->system_information->version; ?>">
<script src="<?php echo $config["assets"]. "js" . DS . "replacestate.js";?>"></script>


